/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStrovaCreditToken,
  IStrovaCreditTokenInterface,
} from "../../contracts/IStrovaCreditToken";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mintAuthority",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newAuthority",
        type: "address",
      },
    ],
    name: "transferMintAuthority",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStrovaCreditToken__factory {
  static readonly abi = _abi;
  static createInterface(): IStrovaCreditTokenInterface {
    return new Interface(_abi) as IStrovaCreditTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStrovaCreditToken {
    return new Contract(address, _abi, runner) as unknown as IStrovaCreditToken;
  }
}
