/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStrovaCreditToken } from "./IStrovaCreditToken";
export type { StrovaCreditToken } from "./StrovaCreditToken";
export type { SyncContract } from "./SyncContract";
export type { SyncContractProxy } from "./SyncContractProxy";
