/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISyncoraCreditToken } from "./ISyncoraCreditToken";
export type { SyncContract } from "./SyncContract";
export type { SyncContractProxy } from "./SyncContractProxy";
export type { SyncoraCreditToken } from "./SyncoraCreditToken";
