/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SyncContract {
  export type DataHeaderStruct = {
    primaryCategory: BytesLike;
    secondaryCategory: BytesLike;
  };

  export type DataHeaderStructOutput = [
    primaryCategory: string,
    secondaryCategory: string
  ] & { primaryCategory: string; secondaryCategory: string };

  export type AgentResponseStruct = {
    agent: AddressLike;
    isValid: boolean;
    isSeedDeleted: boolean;
    hasRating: boolean;
    rating: BigNumberish;
    calculatedCredits: BigNumberish;
    hasSyntheticDataLink: boolean;
    syntheticDataLink: BytesLike;
  };

  export type AgentResponseStructOutput = [
    agent: string,
    isValid: boolean,
    isSeedDeleted: boolean,
    hasRating: boolean,
    rating: bigint,
    calculatedCredits: bigint,
    hasSyntheticDataLink: boolean,
    syntheticDataLink: string
  ] & {
    agent: string;
    isValid: boolean;
    isSeedDeleted: boolean;
    hasRating: boolean;
    rating: bigint;
    calculatedCredits: bigint;
    hasSyntheticDataLink: boolean;
    syntheticDataLink: string;
  };

  export type DataSubmissionStruct = {
    exists: boolean;
    user: AddressLike;
    timestamp: BigNumberish;
    domain: string;
    dataType: string;
    dataFormat: string;
    fileSizeInKB: BigNumberish;
    dataLink: BytesLike;
    header: SyncContract.DataHeaderStruct;
    isRated: boolean;
    response: SyncContract.AgentResponseStruct;
  };

  export type DataSubmissionStructOutput = [
    exists: boolean,
    user: string,
    timestamp: bigint,
    domain: string,
    dataType: string,
    dataFormat: string,
    fileSizeInKB: bigint,
    dataLink: string,
    header: SyncContract.DataHeaderStructOutput,
    isRated: boolean,
    response: SyncContract.AgentResponseStructOutput
  ] & {
    exists: boolean;
    user: string;
    timestamp: bigint;
    domain: string;
    dataType: string;
    dataFormat: string;
    fileSizeInKB: bigint;
    dataLink: string;
    header: SyncContract.DataHeaderStructOutput;
    isRated: boolean;
    response: SyncContract.AgentResponseStructOutput;
  };

  export type SubmissionSummaryStruct = {
    dataKey: BytesLike;
    user: AddressLike;
    timestamp: BigNumberish;
    dataLink: string;
    domain: string;
    dataType: string;
    dataFormat: string;
    fileSizeInKB: BigNumberish;
    primaryCategory: BytesLike;
    secondaryCategory: BytesLike;
    isRated: boolean;
  };

  export type SubmissionSummaryStructOutput = [
    dataKey: string,
    user: string,
    timestamp: bigint,
    dataLink: string,
    domain: string,
    dataType: string,
    dataFormat: string,
    fileSizeInKB: bigint,
    primaryCategory: string,
    secondaryCategory: string,
    isRated: boolean
  ] & {
    dataKey: string;
    user: string;
    timestamp: bigint;
    dataLink: string;
    domain: string;
    dataType: string;
    dataFormat: string;
    fileSizeInKB: bigint;
    primaryCategory: string;
    secondaryCategory: string;
    isRated: boolean;
  };
}

export interface SyncContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DATA_LINK_SIZE"
      | "PRIMARY_CATEGORY_SIZE"
      | "SECONDARY_CATEGORY_SIZE"
      | "UPGRADE_INTERFACE_VERSION"
      | "accumulatedCredits"
      | "admin"
      | "agentConfigs"
      | "allowAgent"
      | "claimCredits"
      | "createAgent"
      | "creditToken"
      | "getSubmission"
      | "getSubmissionKey"
      | "getUserSubmissionKeyAt"
      | "getUserSubmissionKeys"
      | "getUserSubmissionSummaries"
      | "initialize"
      | "proxiableUUID"
      | "rateData"
      | "submitData"
      | "transferAdmin"
      | "transferMintAuthority"
      | "upgradeToAndCall"
      | "userSubmissionCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "AgentAllowed"
      | "AgentCreated"
      | "CreditsClaimed"
      | "DataRated"
      | "DataSubmitted"
      | "Initialized(uint64)"
      | "Initialized(address,address)"
      | "MintAuthorityTransferred"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DATA_LINK_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRIMARY_CATEGORY_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDARY_CATEGORY_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedCredits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "agentConfigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCredits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmissionKey",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubmissionKeyAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubmissionKeys",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubmissionSummaries",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateData",
    values: [
      string,
      boolean,
      boolean,
      boolean,
      BigNumberish,
      boolean,
      string,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitData",
    values: [string, string, string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferMintAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userSubmissionCount",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DATA_LINK_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRIMARY_CATEGORY_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDARY_CATEGORY_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmissionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubmissionKeyAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubmissionKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubmissionSummaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rateData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferMintAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSubmissionCount",
    data: BytesLike
  ): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentAllowedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentCreatedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    credits: BigNumberish,
    tokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    credits: bigint,
    tokenAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    credits: bigint;
    tokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataRatedEvent {
  export type InputTuple = [
    dataKey: BytesLike,
    agent: AddressLike,
    user: AddressLike,
    isValid: boolean,
    hasRating: boolean,
    rating: BigNumberish,
    calculatedCredits: BigNumberish,
    sendTokensImmediately: boolean
  ];
  export type OutputTuple = [
    dataKey: string,
    agent: string,
    user: string,
    isValid: boolean,
    hasRating: boolean,
    rating: bigint,
    calculatedCredits: bigint,
    sendTokensImmediately: boolean
  ];
  export interface OutputObject {
    dataKey: string;
    agent: string;
    user: string;
    isValid: boolean;
    hasRating: boolean;
    rating: bigint;
    calculatedCredits: bigint;
    sendTokensImmediately: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataSubmittedEvent {
  export type InputTuple = [
    dataKey: BytesLike,
    user: AddressLike,
    dataLink: string
  ];
  export type OutputTuple = [dataKey: string, user: string, dataLink: string];
  export interface OutputObject {
    dataKey: string;
    user: string;
    dataLink: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Initialized_uint64_Event {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace Initialized_address_address_Event {
  export type InputTuple = [admin: AddressLike, creditToken: AddressLike];
  export type OutputTuple = [admin: string, creditToken: string];
  export interface OutputObject {
    admin: string;
    creditToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintAuthorityTransferredEvent {
  export type InputTuple = [newAuthority: AddressLike];
  export type OutputTuple = [newAuthority: string];
  export interface OutputObject {
    newAuthority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SyncContract extends BaseContract {
  connect(runner?: ContractRunner | null): SyncContract;
  waitForDeployment(): Promise<this>;

  interface: SyncContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DATA_LINK_SIZE: TypedContractMethod<[], [bigint], "view">;

  PRIMARY_CATEGORY_SIZE: TypedContractMethod<[], [bigint], "view">;

  SECONDARY_CATEGORY_SIZE: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  accumulatedCredits: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  agentConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, boolean] & { exists: boolean; isEnabled: boolean }],
    "view"
  >;

  allowAgent: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  claimCredits: TypedContractMethod<[], [void], "nonpayable">;

  createAgent: TypedContractMethod<[], [void], "nonpayable">;

  creditToken: TypedContractMethod<[], [string], "view">;

  getSubmission: TypedContractMethod<
    [dataKey: BytesLike],
    [SyncContract.DataSubmissionStructOutput],
    "view"
  >;

  getSubmissionKey: TypedContractMethod<[dataLink: string], [string], "view">;

  getUserSubmissionKeyAt: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;

  getUserSubmissionKeys: TypedContractMethod<
    [user: AddressLike, start: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getUserSubmissionSummaries: TypedContractMethod<
    [user: AddressLike, start: BigNumberish, limit: BigNumberish],
    [SyncContract.SubmissionSummaryStructOutput[]],
    "view"
  >;

  initialize: TypedContractMethod<
    [admin_: AddressLike, creditToken_: AddressLike],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  rateData: TypedContractMethod<
    [
      dataLink: string,
      isSeedDeleted: boolean,
      isValid: boolean,
      hasRating: boolean,
      rating: BigNumberish,
      hasSyntheticDataLink: boolean,
      syntheticDataLink: string,
      sendTokensImmediately: boolean
    ],
    [void],
    "nonpayable"
  >;

  submitData: TypedContractMethod<
    [
      dataLink: string,
      primaryCategory: string,
      secondaryCategory: string,
      domain: string,
      dataType: string,
      dataFormat: string,
      fileSizeInKB: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  transferMintAuthority: TypedContractMethod<
    [newAuthority: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  userSubmissionCount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DATA_LINK_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRIMARY_CATEGORY_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDARY_CATEGORY_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accumulatedCredits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, boolean] & { exists: boolean; isEnabled: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "allowAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimCredits"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAgent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creditToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [dataKey: BytesLike],
    [SyncContract.DataSubmissionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmissionKey"
  ): TypedContractMethod<[dataLink: string], [string], "view">;
  getFunction(
    nameOrSignature: "getUserSubmissionKeyAt"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSubmissionKeys"
  ): TypedContractMethod<
    [user: AddressLike, start: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSubmissionSummaries"
  ): TypedContractMethod<
    [user: AddressLike, start: BigNumberish, limit: BigNumberish],
    [SyncContract.SubmissionSummaryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [admin_: AddressLike, creditToken_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rateData"
  ): TypedContractMethod<
    [
      dataLink: string,
      isSeedDeleted: boolean,
      isValid: boolean,
      hasRating: boolean,
      rating: BigNumberish,
      hasSyntheticDataLink: boolean,
      syntheticDataLink: string,
      sendTokensImmediately: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitData"
  ): TypedContractMethod<
    [
      dataLink: string,
      primaryCategory: string,
      secondaryCategory: string,
      domain: string,
      dataType: string,
      dataFormat: string,
      fileSizeInKB: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferMintAuthority"
  ): TypedContractMethod<[newAuthority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userSubmissionCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "AgentAllowed"
  ): TypedContractEvent<
    AgentAllowedEvent.InputTuple,
    AgentAllowedEvent.OutputTuple,
    AgentAllowedEvent.OutputObject
  >;
  getEvent(
    key: "AgentCreated"
  ): TypedContractEvent<
    AgentCreatedEvent.InputTuple,
    AgentCreatedEvent.OutputTuple,
    AgentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CreditsClaimed"
  ): TypedContractEvent<
    CreditsClaimedEvent.InputTuple,
    CreditsClaimedEvent.OutputTuple,
    CreditsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DataRated"
  ): TypedContractEvent<
    DataRatedEvent.InputTuple,
    DataRatedEvent.OutputTuple,
    DataRatedEvent.OutputObject
  >;
  getEvent(
    key: "DataSubmitted"
  ): TypedContractEvent<
    DataSubmittedEvent.InputTuple,
    DataSubmittedEvent.OutputTuple,
    DataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized(uint64)"
  ): TypedContractEvent<
    Initialized_uint64_Event.InputTuple,
    Initialized_uint64_Event.OutputTuple,
    Initialized_uint64_Event.OutputObject
  >;
  getEvent(
    key: "Initialized(address,address)"
  ): TypedContractEvent<
    Initialized_address_address_Event.InputTuple,
    Initialized_address_address_Event.OutputTuple,
    Initialized_address_address_Event.OutputObject
  >;
  getEvent(
    key: "MintAuthorityTransferred"
  ): TypedContractEvent<
    MintAuthorityTransferredEvent.InputTuple,
    MintAuthorityTransferredEvent.OutputTuple,
    MintAuthorityTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "AgentAllowed(address)": TypedContractEvent<
      AgentAllowedEvent.InputTuple,
      AgentAllowedEvent.OutputTuple,
      AgentAllowedEvent.OutputObject
    >;
    AgentAllowed: TypedContractEvent<
      AgentAllowedEvent.InputTuple,
      AgentAllowedEvent.OutputTuple,
      AgentAllowedEvent.OutputObject
    >;

    "AgentCreated(address)": TypedContractEvent<
      AgentCreatedEvent.InputTuple,
      AgentCreatedEvent.OutputTuple,
      AgentCreatedEvent.OutputObject
    >;
    AgentCreated: TypedContractEvent<
      AgentCreatedEvent.InputTuple,
      AgentCreatedEvent.OutputTuple,
      AgentCreatedEvent.OutputObject
    >;

    "CreditsClaimed(address,uint256,uint256)": TypedContractEvent<
      CreditsClaimedEvent.InputTuple,
      CreditsClaimedEvent.OutputTuple,
      CreditsClaimedEvent.OutputObject
    >;
    CreditsClaimed: TypedContractEvent<
      CreditsClaimedEvent.InputTuple,
      CreditsClaimedEvent.OutputTuple,
      CreditsClaimedEvent.OutputObject
    >;

    "DataRated(bytes32,address,address,bool,bool,uint8,uint256,bool)": TypedContractEvent<
      DataRatedEvent.InputTuple,
      DataRatedEvent.OutputTuple,
      DataRatedEvent.OutputObject
    >;
    DataRated: TypedContractEvent<
      DataRatedEvent.InputTuple,
      DataRatedEvent.OutputTuple,
      DataRatedEvent.OutputObject
    >;

    "DataSubmitted(bytes32,address,string)": TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;
    DataSubmitted: TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      Initialized_uint64_Event.InputTuple,
      Initialized_uint64_Event.OutputTuple,
      Initialized_uint64_Event.OutputObject
    >;
    "Initialized(address,address)": TypedContractEvent<
      Initialized_address_address_Event.InputTuple,
      Initialized_address_address_Event.OutputTuple,
      Initialized_address_address_Event.OutputObject
    >;

    "MintAuthorityTransferred(address)": TypedContractEvent<
      MintAuthorityTransferredEvent.InputTuple,
      MintAuthorityTransferredEvent.OutputTuple,
      MintAuthorityTransferredEvent.OutputObject
    >;
    MintAuthorityTransferred: TypedContractEvent<
      MintAuthorityTransferredEvent.InputTuple,
      MintAuthorityTransferredEvent.OutputTuple,
      MintAuthorityTransferredEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
